name: CI

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    with:
      directory: test
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # TODO: Add test run for 'CD' workflow
